/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-10-03 05:24:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>GloceryNow - Home</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("	font-family: Arial, sans-serif;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	max-width: 1200px;\r\n");
      out.write("	margin: 40px auto;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	background-color: #f9f9f9;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories {\r\n");
      out.write("	background-color: #f0f0f0;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	border-bottom: 1px solid #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories ul {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories li {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: #337ab7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories a:hover {\r\n");
      out.write("	color: #23527c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".products {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-md-3 {\r\n");
      out.write("	width: 25%;\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card img {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 150px;\r\n");
      out.write("	object-fit: cover;\r\n");
      out.write("	border-radius: 10px 10px 0 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card h3 {\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card p {\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card button {\r\n");
      out.write("	background-color: #337ab7;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border: none;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card button:hover {\r\n");
      out.write("	background-color: #23527c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-button {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 20px;\r\n");
      out.write("	right: 20px;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("	background-color: #337ab7;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border: none;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	background-color: #337ab7\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-button:hover {\r\n");
      out.write("	background-color: #23527c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-sidebar {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	right: 0;\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	transform: translateX(100%);\r\n");
      out.write("	transition: transform 0.3s ease-in-out;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-sidebar.open {\r\n");
      out.write("	transform: translateX(0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories {\r\n");
      out.write("	background-color: #f7f7f7;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	border-bottom: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories ul {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories li {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: #337ab7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories a:hover {\r\n");
      out.write("	color: #23527c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories a.active {\r\n");
      out.write("	color: #23527c;\r\n");
      out.write("	border-bottom: 2px solid #337ab7;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h1>GloceryNow - Home</h1>\r\n");
      out.write("		<div class=\"categories\">\r\n");
      out.write("			<h2>Categories</h2>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"#fruits\">Fruits</a></li>\r\n");
      out.write("				<li><a href=\"#vegetables\">Vegetables</a></li>\r\n");
      out.write("				<li><a href=\"#dairy\">Dairy</a></li>\r\n");
      out.write("				<li><a href=\"#meat\">Meat</a></li>\r\n");
      out.write("				<li><a href=\"#poultry\">Poultry</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"products\">\r\n");
      out.write("			<h2 id=\"fruits\">Fruits</h2>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"images/apple.jpg\" alt=\"Apple\">\r\n");
      out.write("						<h3>Apple</h3>\r\n");
      out.write("						<p class=\"price\">Price: $1.99</p>\r\n");
      out.write("						<p class=\"quantity\">Quantity: 1 kg</p>\r\n");
      out.write("						<p>Category: Fruits</p>\r\n");
      out.write("						<button class=\"add-to-cart\" onclick=\"addInCart(this)\">Add\r\n");
      out.write("							to Cart</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"images/banana.jpg\" alt=\"Banana\">\r\n");
      out.write("						<h3>Banana</h3>\r\n");
      out.write("						<p class=\"price\">Price: $0.99</p>\r\n");
      out.write("						<p class=\"quantity\">Quantity: 1 kg</p>\r\n");
      out.write("						<p>Category: Fruits</p>\r\n");
      out.write("						<button class=\"add-to-cart\" onclick=\"addInCart(this)\">Add\r\n");
      out.write("							to Cart</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"images/orange.jpg\" alt=\"Orange\">\r\n");
      out.write("						<h3>Orange</h3>\r\n");
      out.write("						<p class=\"price\">Price: $1.49</p>\r\n");
      out.write("						<p class=\"quantity\">Quantity: 1 kg</p>\r\n");
      out.write("						<p>Category: Fruits</p>\r\n");
      out.write("						<button class=\"add-to-cart\" onclick=\"addInCart(this)\">Add\r\n");
      out.write("							to Cart</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<h2 id=\"vegetables\">Vegetables</h2>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"images/carrot.jpg\" alt=\"Carrot\">\r\n");
      out.write("						<h3>Carrot</h3>\r\n");
      out.write("						<p class=\"price\">Price: $1.49</p>\r\n");
      out.write("						<p class=\"quantity\">Quantity: 1 kg</p>\r\n");
      out.write("						<p>Category: Vegetables</p>\r\n");
      out.write("						<button class=\"add-to-cart\" onclick=\"addInCart(this)\">Add\r\n");
      out.write("							to Cart</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"images/broccoli.jpg\" alt=\"Broccoli\">\r\n");
      out.write("						<h3>Broccoli</h3>\r\n");
      out.write("						<p class=\"price\">Price: $1.99</p>\r\n");
      out.write("						<p class=\"quantity\">Quantity: 1 kg</p>\r\n");
      out.write("						<p>Category: Vegetables</p>\r\n");
      out.write("						<button class=\"add-to-cart\" onclick=\"addInCart(this)\">Add\r\n");
      out.write("							to Cart</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"images/cauliflower.jpg\" alt=\"Cauliflower\">\r\n");
      out.write("						<h3>Cauliflower</h3>\r\n");
      out.write("						<p class=\"price\">Price: $1.99</p>\r\n");
      out.write("						<p class=\"quantity\">Quantity: 1 kg</p>\r\n");
      out.write("						<p>Category: Vegetables</p>\r\n");
      out.write("						<button class=\"add-to-cart\" onclick=\"addInCart(this)\">Add\r\n");
      out.write("							to Cart</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<h2 id=\"dairy\">Dairy</h2>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"images/milk.jpg \" alt=\"Milk\">\r\n");
      out.write("						<h3>Milk</h3>\r\n");
      out.write("						<p class=\"price\">Price: $2.99</p>\r\n");
      out.write("						<p class=\"quantity\">Quantity: 1 liter</p>\r\n");
      out.write("						<p>Category: Dairy</p>\r\n");
      out.write("						<button class=\"add-to-cart\" onclick=\"addInCart(this)\">Add\r\n");
      out.write("							to Cart</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"images/cheese.jpg\" alt=\"Cheese\">\r\n");
      out.write("						<h3>Cheese</h3>\r\n");
      out.write("						<p class=\"price\">Price: $3.99</p>\r\n");
      out.write("						<p class=\"quantity\">Quantity: 1 kg</p>\r\n");
      out.write("						<p>Category: Dairy</p>\r\n");
      out.write("						<button class=\"add-to-cart\" onclick=\"addInCart(this)\">Add\r\n");
      out.write("							to Cart</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"images/yogurt.jpg\" alt=\"Yogurt\">\r\n");
      out.write("						<h3>Yogurt</h3>\r\n");
      out.write("						<p class=\"price\">Price: $2.99</p>\r\n");
      out.write("						<p class=\"quantity\">Quantity: 1 kg</p>\r\n");
      out.write("						<p>Category: Dairy</p>\r\n");
      out.write("						<button class=\"add-to-cart\" onclick=\"addInCart(this)\">Add\r\n");
      out.write("							to Cart</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<h2 id=\"meat\">Meat</h2>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"images/chicken.jpg\" alt=\"Chicken\">\r\n");
      out.write("						<h3>Chicken</h3>\r\n");
      out.write("						<p class=\"price\">Price: $3.99</p>\r\n");
      out.write("						<p class=\"quantity\">Quantity: 1 kg</p>\r\n");
      out.write("						<p>Category: Meat</p>\r\n");
      out.write("						<button class=\"add-to-cart\" onclick=\"addInCart(this)\">Add\r\n");
      out.write("							to Cart</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"images/beef.jpg\" alt=\"Beef\">\r\n");
      out.write("						<h3>Beef</h3>\r\n");
      out.write("						<p class=\"price\">Price: $4.99</p>\r\n");
      out.write("						<p class=\"quantity\">Quantity: 1 kg</p>\r\n");
      out.write("						<p>Category: Meat</p>\r\n");
      out.write("						<button class=\"add-to-cart\" onclick=\"addInCart(this)\">Add\r\n");
      out.write("							to Cart</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"images/pork.jpg\" alt=\"Pork\">\r\n");
      out.write("						<h3>Pork</h3>\r\n");
      out.write("						<p class=\"price\">Price: $3.99</p>\r\n");
      out.write("						<p class=\"quantity\">Quantity: 1 kg</p>\r\n");
      out.write("						<p>Category: Meat</p>\r\n");
      out.write("						<button class=\"add-to-cart\" onclick=\"addInCart(this)\">Add\r\n");
      out.write("							to Cart</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<h2 id=\"poultry\">Poultry</h2>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"images/turkey.jpg\" alt=\"Turkey\">\r\n");
      out.write("						<h3>Turkey</h3>\r\n");
      out.write("						<p class=\"price\">Price: $4.99</p>\r\n");
      out.write("						<p class=\"quantity\">Quantity: 1 kg</p>\r\n");
      out.write("						<p>Category: Poultry</p>\r\n");
      out.write("						<button class=\"add-to-cart\" onclick=\"addInCart(this)\">Add\r\n");
      out.write("							to Cart</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"images/duck.jpg\" alt=\"Duck\">\r\n");
      out.write("						<h3>Duck</h3>\r\n");
      out.write("						<p class=\"price\">Price: $4.99</p>\r\n");
      out.write("						<p class=\"quantity\">Quantity: 1 kg</p>\r\n");
      out.write("						<p>Category: Poultry</p>\r\n");
      out.write("						<button class=\"add-to-cart\" onclick=\"addInCart(this)\">Add\r\n");
      out.write("							to Cart</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"images/goose.jpg\" alt=\"Goose\">\r\n");
      out.write("						<h3>Goose</h3>\r\n");
      out.write("						<p class=\"price\">Price: $4.99</p>\r\n");
      out.write("						<p class=\"quantity\">Quantity: 1 kg</p>\r\n");
      out.write("						<p>Category: Poultry</p>\r\n");
      out.write("						<button class=\"add-to-cart\" onclick=\"addInCart(this)\">Add\r\n");
      out.write("							to Cart</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<button class=\"cart-button\" onclick=\"toggleCart()\">Cart</button>\r\n");
      out.write("		<div class=\"cart-sidebar\">\r\n");
      out.write("			<h2>Cart</h2>\r\n");
      out.write("			<ul class=\"cart-list\">\r\n");
      out.write("				<!-- Cart items will be added here -->\r\n");
      out.write("			</ul>\r\n");
      out.write("			<p>Total: $0.00</p>\r\n");
      out.write("			<button class=\"checkout-button\">Checkout</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("    \r\n");
      out.write("    document.querySelectorAll('.categories a').forEach((link) => {\r\n");
      out.write("        link.addEventListener('click', (event) => {\r\n");
      out.write("            event.preventDefault();\r\n");
      out.write("            let sectionId = link.getAttribute('href');\r\n");
      out.write("            let section = document.querySelector(sectionId);\r\n");
      out.write("            section.scrollIntoView({ behavior: 'smooth' });\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function toggleCart() {\r\n");
      out.write("        var cartSidebar = document.querySelector('.cart-sidebar');\r\n");
      out.write("        cartSidebar.classList.toggle('open');\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
