/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-11-14 18:05:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import javax.persistence.Query;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.EntityManagerFactory;
import model.Product;
import java.util.List;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Connection;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(11);
    _jspx_imports_classes.add("model.Product");
    _jspx_imports_classes.add("javax.persistence.Query");
    _jspx_imports_classes.add("javax.persistence.Persistence");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("javax.persistence.EntityManagerFactory");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("javax.persistence.EntityManager");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>GloceryNow - Home</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("	font-family: Arial, sans-serif;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	background-color: #f9f9f9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	max-width: 1200px;\r\n");
      out.write("	margin: 40px auto;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	animation: fadeIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header {\r\n");
      out.write("	background-color: #337ab7;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	border-bottom: 1px solid #ddd;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	animation: slideIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .logo {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	animation: bounceIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .buttons {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .buttons button {\r\n");
      out.write("	background-color: #337ab7;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border: none;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	transition: background-color 0.2s ease-in-out;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("	animation: fadeIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header .buttons button:hover {\r\n");
      out.write("	background-color: #23527c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-bar {\r\n");
      out.write("	background-color: #f0f0f0;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	border-bottom: 1px solid #ddd;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	animation: slideIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-bar input {\r\n");
      out.write("	width: 70%;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	animation: fadeIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-bar button {\r\n");
      out.write("	background-color: #337ab7;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border: none;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	transition: background-color 0.2s ease-in-out;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("	animation: fadeIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-bar button:hover {\r\n");
      out.write("	background-color: #23527c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories {\r\n");
      out.write("	background-color: #f0f0f0;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	border-bottom: 1px solid #ddd;\r\n");
      out.write("	animation: slideIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories .row {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories .col-md-3 {\r\n");
      out.write("	width: 25%;\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories .card {\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	transition: transform 0.2s ease-in-out;\r\n");
      out.write("	animation: fadeIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories .card:hover {\r\n");
      out.write("	transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories .card img {\r\n");
      out.write("	object-fit: cover;\r\n");
      out.write("	object-position: 100% 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 230px;\r\n");
      out.write("	animation: zoomIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories .card h3 {\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	animation: fadeIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".categories .card p {\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	animation: fadeIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".trending-products {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	animation: slideIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".trending-products h2 {\r\n");
      out.write("	margin-top: 0;\r\n");
      out.write("	animation: fadeIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".trending-products .row {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".trending-products .col-md-3 {\r\n");
      out.write("	width: 25%;\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".trending-products .card {\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	transition: transform 0.2s ease-in-out;\r\n");
      out.write("	animation: fadeIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".trending-products .card:hover {\r\n");
      out.write("	transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".trending-products .card img {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 150px;\r\n");
      out.write("	object-fit: contain;\r\n");
      out.write("	border-radius: 10px 10px 0 0;\r\n");
      out.write("	animation: zoomIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".trending-products .card h3 {\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	animation: fadeIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".trending-products .card p {\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	animation: fadeIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".trending-products .card button {\r\n");
      out.write("	background-color: #337ab7;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border: none;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	transition: background-color 0.2s ease-in-out;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	animation: fadeIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".trending-products .card button:hover {\r\n");
      out.write("	background-color: #23527c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-sidebar {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	right: 0;\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	border: 1px solid #ddd;\r\n");
      out.write("	box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	transform: translateX(100%);\r\n");
      out.write("	transition: transform 0.3s ease-in-out;\r\n");
      out.write("	animation: slideIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-sidebar.open {\r\n");
      out.write("	transform: translate X(0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-sidebar h2 {\r\n");
      out.write("	margin-top: 0;\r\n");
      out.write("	animation: fadeIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-sidebar ul {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-sidebar li {\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	animation: fadeIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-sidebar p {\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	animation: fadeIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cart-sidebar button {\r\n");
      out.write("	background-color: #337ab7;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border: none;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	transition: background-color 0.2s ease-in-out;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("	animation: fadeIn 1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@\r\n");
      out.write("keyframes fadeIn {from { opacity:0;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("@\r\n");
      out.write("keyframes slideIn {from { transform:translateX(-100%);\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("	transform: translateX(0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("@\r\n");
      out.write("keyframes bounceIn {from { transform:scale(0.5);\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("	transform: scale(1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("@\r\n");
      out.write("keyframes zoomIn {from { transform:scale(0.5);\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("	transform: scale(1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".admin-footer {\r\n");
      out.write("	background-color: #f0f0f0;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	clear: both;\r\n");
      out.write("	border-top: 1px solid #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".admin-footer p {\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"header\">\r\n");
      out.write("		<h1 class=\"logo\">GloceryNow</h1>\r\n");
      out.write("		<div class=\"buttons\">\r\n");
      out.write("			<button class=\"cart-button\" onclick=\"toggleCart()\">Cart</button>\r\n");
      out.write("			<form action=\"logout\" method=\"get\">\r\n");
      out.write("				<button class=\"logout-button\" type=\"submit\">Logout</button>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"search-bar\">\r\n");
      out.write("			<input type=\"search\" placeholder=\"Search products...\">\r\n");
      out.write("			<button>Search</button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"trending-products\">\r\n");
      out.write("			<h2>Trending Products</h2>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				");

				EntityManagerFactory emf = Persistence.createEntityManagerFactory("shop");
				EntityManager em = emf.createEntityManager();
				Query query = em.createQuery("select p from Product p");
				List<Product> productList = query.getResultList();
				if (productList != null) {
					for (Product product : productList) {
				
      out.write("\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img src=\"");
      out.print(product.getImage());
      out.write("\" alt=\"product\">\r\n");
      out.write("						<h3>");
      out.print(product.getName());
      out.write("</h3>\r\n");
      out.write("						<p class=\"price\">\r\n");
      out.write("							Price: ‍₹");
      out.print(product.getPrice());
      out.write("</p>\r\n");
      out.write("						<p class=\"quantity\">\r\n");
      out.write("							Quantity:\r\n");
      out.write("							");
      out.print(product.getQuantity());
      out.write("\r\n");
      out.write("							");
      out.print(product.getQuantityUnit());
      out.write("</p>\r\n");
      out.write("						<button class=\"add-to-cart\" onclick=\"addInCart(this)\">Add\r\n");
      out.write("							to Cart</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"categories\">\r\n");
      out.write("			<h2>Categories</h2>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-2_10.png\"\r\n");
      out.write("							alt=\"Dairy, Bread & Eggs\">\r\n");
      out.write("						<h3>Dairy, Bread & Eggs</h3>\r\n");
      out.write("						<p>Explore our wide range of dairy products</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-3_9.png\"\r\n");
      out.write("							alt=\"Fruits & Vegetables\">\r\n");
      out.write("						<h3>Fruits & Vegetables</h3>\r\n");
      out.write("						<p>Get fresh fruits delivered to your doorstep</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\" card\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-4_9.png\"\r\n");
      out.write("							alt=\"Cold Drinks & Juices\">\r\n");
      out.write("						<h3>Cold Drinks & Juices</h3>\r\n");
      out.write("						<p>Explore our wide range of fresh vegetables</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-5_4.png\"\r\n");
      out.write("							alt=\"Snacks & Munchies\">\r\n");
      out.write("						<h3>Snacks & Munchies</h3>\r\n");
      out.write("						<p>Get freshly baked bread and pastries delivered</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-6_5.png\"\r\n");
      out.write("							alt=\"Breakfast & Instant Food\">\r\n");
      out.write("						<h3>Breakfast & Instant Food</h3>\r\n");
      out.write("						<p>Explore our wide range of meat and fish products</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-7_3.png\"\r\n");
      out.write("							alt=\"Sweets\">\r\n");
      out.write("						<h3>Sweets</h3>\r\n");
      out.write("						<p>Get your favorite snacks delivered to your doorstep</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-8_4.png\"\r\n");
      out.write("							alt=\"Biscuits & Bakery\">\r\n");
      out.write("						<h3>Biscuits & Bakery</h3>\r\n");
      out.write("						<p>Explore our wide range of beverages</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-17.png\"\r\n");
      out.write("							alt=\"Cleaning Essentials\">\r\n");
      out.write("						<h3>Cleaning Essentials</h3>\r\n");
      out.write("						<p>Get household essentials delivered to your doorstep</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/layout-engine/2022-11/Slice-19.png\"\r\n");
      out.write("							alt=\"Personal care\">\r\n");
      out.write("						<h3>Personal care</h3>\r\n");
      out.write("						<p>Explore our wide range of personal care products</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"cart-sidebar\">\r\n");
      out.write("		<h2>Cart</h2>\r\n");
      out.write("		<ul class=\"cart-list\">\r\n");
      out.write("			<!-- Cart items will be added here -->\r\n");
      out.write("		</ul>\r\n");
      out.write("		<p>Total: $0.00</p>\r\n");
      out.write("		<button class=\"checkout-button\">Checkout</button>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"admin-footer\">\r\n");
      out.write("		<p>Made With ❤ &copy; 2024 GloceryNow</p>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		document.querySelectorAll('.categories .card').forEach((card) => {\r\n");
      out.write("			card.addEventListener('mouseover', (event) => {\r\n");
      out.write("				card.style.transform = 'scale(1.05)';\r\n");
      out.write("			});\r\n");
      out.write("			card.addEventListener('mouseout', (event) => {\r\n");
      out.write("				card.style.transform = 'scale(1)';\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		function toggleCart() {\r\n");
      out.write("			var cartSidebar = document.querySelector('.cart-sidebar');\r\n");
      out.write("			cartSidebar.classList.toggle('open');\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function addInCart(element) {\r\n");
      out.write("			// Add the product to the cart\r\n");
      out.write("			var product = element.parentNode;\r\n");
      out.write("			var productName = product.querySelector('h3').textContent;\r\n");
      out.write("			var productPrice = product.querySelector('.price').textContent;\r\n");
      out.write("			var productQuantity = product.querySelector('.quantity').textContent;\r\n");
      out.write("			var cartList = document.querySelector('.cart-list');\r\n");
      out.write("			var cartItem = document.createElement('li');\r\n");
      out.write("			cart Item.textContent = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productPrice}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productQuantity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("			cartList.appendChild(cartItem);\r\n");
      out.write("			updateTotal();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function updateTotal() {\r\n");
      out.write("			var cartList = document.querySelector('.cart-list');\r\n");
      out.write("			var total = 0;\r\n");
      out.write("			cartList.querySelectorAll('li').forEach((item) => {\r\n");
      out.write("				var price = item.textContent.split(' - ')[1];\r\n");
      out.write("				total += parseFloat(price.replace('$', ''));\r\n");
      out.write("			});\r\n");
      out.write("			document.querySelector('.cart-sidebar p').textContent = `Total: $");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${total.toFixed(2)}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function logout() {\r\n");
      out.write("			// Logout functionality goes here\r\n");
      out.write("			alert('You have been logged out!');\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
